In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report,confusion_matrix
import datetime as dt
from datetime import datetime
import pymysql
import MySQLdb

ModuleNotFoundError: No module named 'MySQLdb'

In [6]:
conn = pymysql.connect(host='127.0.0.1', user='root',password='chchboss',database='mo')

cur = conn.cursor()
sql = "SELECT * FROM location_test"
cur.execute(sql)
results = cur.fetchall()
conn.commit()

#print(results)

location_id = []
user_id = []
longitude = []
latitude = []
start_date = []
start_time = []
duration = []
weekday = []
name1 = []
name2 = []
name3 = []
name4 = []
name5 = []
category1 = []
category2 = []
category3 = []
category4 = []
category5 = []
#user_location_id = []

for row in results:
    location_id.append(row[0])
    user_id.append(row[1])
    longitude.append(row[2])
    latitude.append(row[3])
    start_date.append(row[4])
    start_time.append(row[5])
    duration.append(row[6])
    weekday.append(row[7])
    name1.append(row[8])
    name2.append(row[9])
    name3.append(row[10])
    name4.append(row[11])
    name5.append(row[12])
    category1.append(row[13])
    category2.append(row[14])
    category3.append(row[15])
    category4.append(row[16])
    category5.append(row[17])
    #user_location_id.append(row[18])

all_data = {
    "location_id":location_id,
    "user_id":user_id,
    "longitude":longitude,
    "latitude":latitude,
    "start_date":start_date,
    "start_time":start_time,
    "duration":duration,
    "weekday":weekday,
    "name1":name1,
    "name2":name2,
    "name3":name3,
    "name4":name4,
    "name5":name5,
    "category1":category1,
    "category2":category2,
    "category3":category3,
    "category4":category4,
    "category5":category5
    #"user_location_id":user_location_id

}
df = pd.DataFrame(all_data)
df.head()

,user_id,longitude,latitude,start_date,start_time,duration,weekday,name1,name2,name3,name4,name5,category1,category2,category3,category4,category5
0,2,121.543847,25.052023,2020-08-20,12:35,None,5,Nanjing Fuxing Station,梅花廳(粵菜飲茶) - 兄弟大飯店,Brother Hotel,HONG KONG tea stalls (Nanjing flagship store),恆逸教育訓練中心,transit_station,restaurant,lodging,restaurant,point_of_interest
1,2,121.543847,25.052023,2020-08-20,12:35,None,5,Nanjing Fuxing Station,梅花廳(粵菜飲茶) - 兄弟大飯店,Brother Hotel,HONG KONG tea stalls (Nanjing flagship store),恆逸教育訓練中心,transit_station,restaurant,lodging,restaurant,point_of_interest
2,2,121.543539,25.029342,2020-08-20,12:40,None,5,Taipei Fullerton Hotel-Fuxing South,CUPETIT 卡柏蒂法式手工喜餅,臺北市立大安高級工業職業學校,小樽早餐店,Da-An Vocational High School,lodging,bakery,secondary_school,restaurant,transit_station
3,2,121.559407,25.017759,2020-08-20,12:46,None,5,Linguang Station,7-ELEVEN麟運門市,Taiwan Insect Museum,和記豆漿店,McDonald's,subway_station,convenience_store,museum,restaurant,restaurant
4,2,121.558525,24.998611,2020-08-20,12:51,None,5,85度c,Louisa Coffee 路易．莎咖啡(萬芳醫院店),Cut髮院 百元剪髮專門店 萬芳店,Wanfang Hospital,Wanfang Hospital Station,cafe,cafe,beauty_salon,hospital,subway_station

In [ ]:
stopLoc = df.loc[location['user_id'] == 2 ]

stopLoc = stopLoc.drop(['category3','category4','category5'], 1)
stopLoc['longitude'] = round(stopLoc['longitude'],3)
stopLoc['latitude'] = round(stopLoc['latitude'],3)
stopLoc = stopLoc.reset_index(drop = True)

In [ ]:
def deleteEnter(x):
    enterList = []
    dropList = []

    for a in range(len(stopLoc)):

        #如果這筆是「enter」，記住編號
        if (x.iloc[a,14] == 'entering myPlace'):
            enterList.append(a)

        #如果這筆是「exit」，清空enterList
        elif (x.iloc[a,14] == 'exiting myPlace'):
            enterList = []

        elif (enterList == []):
            pass

        #如果這筆不是進去也不是出來，且有enterList，為要刪除的東西
        elif (enterList != []):
            dropList.append(a) 

    x = x.drop(dropList)
    x = x.reset_index(drop = True)  
    return(x)

stopLoc= deleteEnter(stopLoc)
stopLoc

In [ ]:
for row in range(0,len(stopLoc)-1): 

    #calculate duration
    if stopLoc.iloc[row+1,4] == stopLoc.iloc[row,4]:
        stopLoc.iloc[row,6] = datetime.strptime(stopLoc.iloc[row+1,5], '%H:%M') - datetime.strptime(stopLoc.iloc[row,5], '%H:%M')       
    else:
        a = dt.datetime(2000,1,2,int(stopLoc.iloc[row+1,5].split(':')[0]),int(stopLoc.iloc[row+1,5].split(':')[1]))
        b = dt.datetime(2000,1,1,int(stopLoc.iloc[row,5].split(':')[0]),int(stopLoc.iloc[row,5].split(':')[1]))
        stopLoc.iloc[row,6] = a - b

#delete trivial data, 重複地點太多刪除
dropList = []
for row in range(1,len(stopLoc)-1): 
    if stopLoc.iloc[row,14] != 'entering myPlace' and stopLoc.iloc[row,14] != 'exiting myPlace':
        
        #same longitude and lantitude
        #if stopLoc.iloc[row,2] == stopLoc.iloc[row-1,2] and stopLoc.iloc[row,3] == stopLoc.iloc[row-1,3]:
        #    dropList.append(row)

        #compared with the last record, over 2 place name duplicated will be deleted
        res = set(stopLoc.iloc[row,8:13]) & set(stopLoc.iloc[row-1,8:13])
        #if stopLoc.iloc[row-1,6] < pd.Timedelta('00:10:00'):
        if len(res) > 1: 
            dropList.append(row)

stopLoc = stopLoc.drop(dropList)
stopLoc = stopLoc.reset_index(drop = True)
stopLoc

In [ ]:
for row in range(0,len(stopLoc)-1): 
    #calculate duration
    if stopLoc.iloc[row+1,4] == stopLoc.iloc[row,4]:
        stopLoc.iloc[row,6] = datetime.strptime(stopLoc.iloc[row+1,5], '%H:%M') - datetime.strptime(stopLoc.iloc[row,5], '%H:%M')       
    else:
        a = dt.datetime(2000,1,2,int(stopLoc.iloc[row+1,5].split(':')[0]),int(stopLoc.iloc[row+1,5].split(':')[1]))
        b = dt.datetime(2000,1,1,int(stopLoc.iloc[row,5].split(':')[0]),int(stopLoc.iloc[row,5].split(':')[1]))
        stopLoc.iloc[row,6] = a - b

for row in range(0,len(stopLoc)-1): 

    if stopLoc.iloc[row,6] < pd.Timedelta('00:10:00'):
        stopLoc.iloc[row,13] = 'commute'
stopLoc

In [ ]:
duplicate = []
for row in range(0,len(stopLoc)-1): 

    if stopLoc.iloc[row-1,13] == 'commute' and stopLoc.iloc[row,13] == 'commute':
        duplicate.append(row) 
        
stopLoc = stopLoc.drop(duplicate)
stopLoc = stopLoc.reset_index(drop = True)
        
for row in range(0,len(stopLoc)-1): 
    #calculate duration
    if stopLoc.iloc[row+1,4] == stopLoc.iloc[row,4]:
        stopLoc.iloc[row,6] = datetime.strptime(stopLoc.iloc[row+1,5], '%H:%M') - datetime.strptime(stopLoc.iloc[row,5], '%H:%M')       
    else:
        a = dt.datetime(2000,1,2,int(stopLoc.iloc[row+1,5].split(':')[0]),int(stopLoc.iloc[row+1,5].split(':')[1]))
        b = dt.datetime(2000,1,1,int(stopLoc.iloc[row,5].split(':')[0]),int(stopLoc.iloc[row,5].split(':')[1]))
        stopLoc.iloc[row,6] = a - b
    
stopLoc

In [ ]:
pd.set_option('display.max_rows', 20000)

In [ ]:
stopLoc = stopLoc.drop(['longitude','latitude','name2','name3','name4','name5','category2'], 1)
stopLoc

In [ ]:
stopLoc['end_date'] = stopLoc['start_date']
stopLoc['end_time'] = '23:59' 
for row in range(0,len(stopLoc)-1): 
    stopLoc.iloc[row,8] = stopLoc.iloc[row+1,2]
    stopLoc.iloc[row,9] = stopLoc.iloc[row+1,3]
stopLoc

In [ ]:
#把category1轉map_id
#place_id補上

In [ ]:
category = pd.read_csv("category - location.csv")
category.tail()

In [ ]:
pre_track = pd.merge(stopLoc, category, how='left', on='category1' )
pre_track